/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.mshowcase.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the InstanceImage service. Represents a row in the &quot;msc_InstanceImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.mshowcase.model.impl.InstanceImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.mshowcase.model.impl.InstanceImageImpl}.
 * </p>
 *
 * @author Aritz Galdos
 * @see InstanceImage
 * @see net.sareweb.mshowcase.model.impl.InstanceImageImpl
 * @see net.sareweb.mshowcase.model.impl.InstanceImageModelImpl
 * @generated
 */
public interface InstanceImageModel extends BaseModel<InstanceImage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a instance image model instance should use the {@link InstanceImage} interface instead.
	 */

	/**
	 * Returns the primary key of this instance image.
	 *
	 * @return the primary key of this instance image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this instance image.
	 *
	 * @param primaryKey the primary key of this instance image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the instance image ID of this instance image.
	 *
	 * @return the instance image ID of this instance image
	 */
	public long getInstanceImageId();

	/**
	 * Sets the instance image ID of this instance image.
	 *
	 * @param InstanceImageId the instance image ID of this instance image
	 */
	public void setInstanceImageId(long InstanceImageId);

	/**
	 * Returns the instance ID of this instance image.
	 *
	 * @return the instance ID of this instance image
	 */
	public long getInstanceId();

	/**
	 * Sets the instance ID of this instance image.
	 *
	 * @param InstanceId the instance ID of this instance image
	 */
	public void setInstanceId(long InstanceId);

	/**
	 * Returns the image ID of this instance image.
	 *
	 * @return the image ID of this instance image
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this instance image.
	 *
	 * @param imageId the image ID of this instance image
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the image u r l of this instance image.
	 *
	 * @return the image u r l of this instance image
	 */
	@AutoEscape
	public String getImageURL();

	/**
	 * Sets the image u r l of this instance image.
	 *
	 * @param imageURL the image u r l of this instance image
	 */
	public void setImageURL(String imageURL);

	/**
	 * Returns the user ID of this instance image.
	 *
	 * @return the user ID of this instance image
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this instance image.
	 *
	 * @param userId the user ID of this instance image
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this instance image.
	 *
	 * @return the user uuid of this instance image
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this instance image.
	 *
	 * @param userUuid the user uuid of this instance image
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this instance image.
	 *
	 * @return the company ID of this instance image
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this instance image.
	 *
	 * @param companyId the company ID of this instance image
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this instance image.
	 *
	 * @return the create date of this instance image
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this instance image.
	 *
	 * @param createDate the create date of this instance image
	 */
	public void setCreateDate(Date createDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(InstanceImage instanceImage);

	public int hashCode();

	public CacheModel<InstanceImage> toCacheModel();

	public InstanceImage toEscapedModel();

	public String toString();

	public String toXmlString();
}