/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.mshowcase.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Location service. Represents a row in the &quot;msc_Location&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.mshowcase.model.impl.LocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.mshowcase.model.impl.LocationImpl}.
 * </p>
 *
 * @author Aritz Galdos
 * @see Location
 * @see net.sareweb.mshowcase.model.impl.LocationImpl
 * @see net.sareweb.mshowcase.model.impl.LocationModelImpl
 * @generated
 */
public interface LocationModel extends BaseModel<Location> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a location model instance should use the {@link Location} interface instead.
	 */

	/**
	 * Returns the primary key of this location.
	 *
	 * @return the primary key of this location
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this location.
	 *
	 * @param primaryKey the primary key of this location
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the location ID of this location.
	 *
	 * @return the location ID of this location
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this location.
	 *
	 * @param locationId the location ID of this location
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the instance ID of this location.
	 *
	 * @return the instance ID of this location
	 */
	public long getInstanceId();

	/**
	 * Sets the instance ID of this location.
	 *
	 * @param InstanceId the instance ID of this location
	 */
	public void setInstanceId(long InstanceId);

	/**
	 * Returns the address of this location.
	 *
	 * @return the address of this location
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this location.
	 *
	 * @param address the address of this location
	 */
	public void setAddress(String address);

	/**
	 * Returns the lat of this location.
	 *
	 * @return the lat of this location
	 */
	public double getLat();

	/**
	 * Sets the lat of this location.
	 *
	 * @param lat the lat of this location
	 */
	public void setLat(double lat);

	/**
	 * Returns the lng of this location.
	 *
	 * @return the lng of this location
	 */
	public double getLng();

	/**
	 * Sets the lng of this location.
	 *
	 * @param lng the lng of this location
	 */
	public void setLng(double lng);

	/**
	 * Returns the phone number of this location.
	 *
	 * @return the phone number of this location
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this location.
	 *
	 * @param phoneNumber the phone number of this location
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the fax number of this location.
	 *
	 * @return the fax number of this location
	 */
	@AutoEscape
	public String getFaxNumber();

	/**
	 * Sets the fax number of this location.
	 *
	 * @param faxNumber the fax number of this location
	 */
	public void setFaxNumber(String faxNumber);

	/**
	 * Returns the image ID of this location.
	 *
	 * @return the image ID of this location
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this location.
	 *
	 * @param imageId the image ID of this location
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the image u r l of this location.
	 *
	 * @return the image u r l of this location
	 */
	@AutoEscape
	public String getImageURL();

	/**
	 * Sets the image u r l of this location.
	 *
	 * @param imageURL the image u r l of this location
	 */
	public void setImageURL(String imageURL);

	/**
	 * Returns the user ID of this location.
	 *
	 * @return the user ID of this location
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this location.
	 *
	 * @param userId the user ID of this location
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this location.
	 *
	 * @return the user uuid of this location
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this location.
	 *
	 * @param userUuid the user uuid of this location
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this location.
	 *
	 * @return the company ID of this location
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this location.
	 *
	 * @param companyId the company ID of this location
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this location.
	 *
	 * @return the create date of this location
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this location.
	 *
	 * @param createDate the create date of this location
	 */
	public void setCreateDate(Date createDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Location location);

	public int hashCode();

	public CacheModel<Location> toCacheModel();

	public Location toEscapedModel();

	public String toString();

	public String toXmlString();
}